; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using MEGA.
[ MEGAinfo ]
ver                               = 10200331-x86_64 macOS            
[ DataSettings ]
datatype                          = snNucleotide                     
containsCodingNuc                 = True                             
missingBaseSymbol                 = ?                                
identicalBaseSymbol               = .                                
gapSymbol                         = -                                
[ ProcessTypes ]
ppAlign                           = true                             
ppMuscle                          = true                             
[ AnalysisSettings ]
Gap Penalties                     = ====================             
Gap Open                          = -2.90                            
Gap Extend                        = 0.00                             
Hydrophobicity Multiplier         = 1.20                             
Memory/Iterations                 = ====================             
Max Memory in MB                  = 2048                             
Max Iterations                    = 16                               
Advanced Options                  = ====================             
Genetic Code                      = Vertebrate Mitochondrial         
Cluster Method (Iterations 1,2)   = UPGMA                            
Cluster Method (Other Iterations) = UPGMA                            
Min Diag Length (Lambda)          = 24                               
GeneticCodeTable                  = FFLLSSSSYY**CCWWLLLLPPPPHHQQRRRRIIMMTTTTNNKKSS**VVVVAAAADDEEGGGG